import { createHash, randomBytes, createHmac } from 'node:crypto';
import { db, sqlite, withSqliteTransactionSync } from '@/db/client';
import { offers, offerHistory, candidateDocuments, users, applications, candidates, jobRequisitions } from '@/db/schema';
import { recordAuditSync } from '@/lib/audit';
import { transitionApplicationInTx } from '@/lib/recruitment-workflow';
import { desc, eq, and, like, or, gte, lte } from 'drizzle-orm';
import { nanoid } from 'nanoid';
import { uploadCandidateDocument } from '@/lib/documents/service';

export const OFFER_STATUSES = ['draft','pending_approval','rejected','approved','sent','accepted','declined','expired','withdrawn','replaced'] as const;
export type OfferStatus = typeof OFFER_STATUSES[number];
export const ACTIVE_OFFER_STATUSES: readonly OfferStatus[] = ['draft','pending_approval','approved','sent'];
const transitions: Record<OfferStatus, readonly OfferStatus[]> = {
  draft:['pending_approval','replaced'], pending_approval:['approved','rejected','replaced'], approved:['sent','withdrawn','replaced'],
  sent:['accepted','declined','expired','withdrawn','replaced'], accepted:[], declined:[], expired:[], withdrawn:[], replaced:[], rejected:['replaced']
};
const ISO_DATE=/^\d{4}-\d{2}-\d{2}$/;
const CURRENCY=/^[A-Z]{3}$/;
const TERMS_MAX=10000;
const BENEFITS_MAX=10000;
const RESPONSE_TOKEN_TTL_MS=7*24*60*60*1000;
const RESPONSE_WINDOW_MS=15*60*1000;
const RESPONSE_MAX_ATTEMPTS=10;

export function canTransitionOfferStatus(from: OfferStatus, to: OfferStatus): boolean { return transitions[from]?.includes(to) ?? false; }
export function formatMoneyMinor(minor:number,currency:string):string { const formatter=new Intl.NumberFormat('en-US',{style:'currency',currency}); const digits=formatter.resolvedOptions().maximumFractionDigits ?? 2; return formatter.format(minor/10**digits); }

export function hashResponseToken(token:string):string { return createHash('sha256').update(token).digest('hex'); }
export function generateResponseToken():string { return randomBytes(32).toString('base64url'); }
function assertActiveOrg(org:string) { const r=sqlite.prepare('SELECT status FROM organizations WHERE id=?').get(org) as any; if(r?.status!=='active') throw new Error('Your organization is currently suspended.'); }
function text(v:string|null|undefined,label:string,max:number,required=false):string|null { const x=(v??'').trim(); if(required&&!x) throw new Error(`${label} is required.`); if(x.length>max) throw new Error(`${label} is too long.`); return x||null; }
function money(v:string|number|undefined,label:string):number { const x=typeof v==='number'?String(v):String(v??'').trim(); if(!/^\d+$/.test(x)) throw new Error(`${label} must be a whole number of minor currency units.`); const n=Number(x); if(!Number.isSafeInteger(n)||n<0) throw new Error(`${label} is invalid.`); return n; }
function date(v:string|undefined,label:string):string|null { if(!v) return null; if(!ISO_DATE.test(v)) throw new Error(`${label} must use YYYY-MM-DD.`); const d=new Date(`${v}T00:00:00.000Z`); if(Number.isNaN(d.getTime())||d.toISOString().slice(0,10)!==v) throw new Error(`${label} is invalid.`); return v; }
function timestamp(v:string|null|undefined,label:string):string|null { if(!v) return null; const d=new Date(ISO_DATE.test(v)?`${v}T23:59:59.999Z`:v); if(Number.isNaN(d.getTime())) throw new Error(`${label} is invalid.`); return d.toISOString(); }
function assertTerms(input:{currency:string;baseSalaryMinor:string|number;payFrequency:string;variableCompMinor?:string|number;joiningBonusMinor?:string|number;allowancesMinor?:string|number;otherCompMinor?:string|number;benefitsSummary?:string;employmentTerms?:string;proposedJoiningDate?:string;expiresAt?:string}, now=Date.now()) {
  const currency=input.currency.trim().toUpperCase(); if(!CURRENCY.test(currency)) throw new Error('Currency must be a 3-letter ISO code.');
  if(!['hourly','weekly','monthly','annual'].includes(input.payFrequency)) throw new Error('Invalid pay frequency.');
  const baseSalaryMinor=money(input.baseSalaryMinor,'Base salary'); const variableCompMinor=money(input.variableCompMinor??0,'Variable compensation'); const joiningBonusMinor=money(input.joiningBonusMinor??0,'Joining bonus'); const allowancesMinor=money(input.allowancesMinor??0,'Allowances'); const otherCompMinor=money(input.otherCompMinor??0,'Other compensation');
  const benefitsSummary=text(input.benefitsSummary,'Benefits summary',BENEFITS_MAX); const employmentTerms=text(input.employmentTerms,'Employment terms',TERMS_MAX); const proposedJoiningDate=date(input.proposedJoiningDate,'Joining date'); const expiresAt=timestamp(input.expiresAt,'Expiration');
  if(expiresAt && new Date(expiresAt).getTime()<=now) throw new Error('Expiration must be in the future.');
  if(proposedJoiningDate && expiresAt && proposedJoiningDate > expiresAt.slice(0,10)) throw new Error('Joining date cannot be after offer expiration.');
  return {currency,baseSalaryMinor,payFrequency:input.payFrequency,variableCompMinor,joiningBonusMinor,allowancesMinor,otherCompMinor,benefitsSummary,employmentTerms,proposedJoiningDate,expiresAt};
}
function app(org:string,id:string):any { const r=sqlite.prepare(`SELECT a.id,a.organization_id,a.status,a.current_stage,a.candidate_id,a.requisition_id,c.first_name,c.last_name,c.email,j.requisition_code,j.title,j.status job_status,j.employment_type,j.location,j.currency job_currency FROM applications a JOIN candidates c ON c.organization_id=a.organization_id AND c.id=a.candidate_id JOIN job_requisitions j ON j.organization_id=a.organization_id AND j.id=a.requisition_id WHERE a.organization_id=? AND a.id=?`).get(org,id); if(!r) throw new Error('Application not found.'); return r; }
function nextReference():string { const year=new Date().getUTCFullYear(); const row=sqlite.prepare("SELECT offer_reference FROM offers WHERE offer_reference LIKE ? ORDER BY offer_reference DESC LIMIT 1").get(`OFF-${year}-%`) as any; const n=row?.offer_reference?Number(String(row.offer_reference).slice(-6))+1:1; if(!Number.isSafeInteger(n)||n>999999) throw new Error('Offer reference capacity exhausted.'); return `OFF-${year}-${String(n).padStart(6,'0')}`; }
function history(org:string,offerId:string,action:string,fromStatus:string|null,toStatus:string|null,actor:string|null,metadata?:Record<string,unknown>) { sqlite.prepare('INSERT INTO offer_history (id,organization_id,offer_id,action,from_status,to_status,actor_user_id,metadata) VALUES (?,?,?,?,?,?,?,?)').run(nanoid(),org,offerId,action,fromStatus,toStatus,actor,metadata?JSON.stringify(metadata):null); }
function audit(org:string,actor:string|null,action:string,id:string,metadata?:Record<string,unknown>) { recordAuditSync({organizationId:org,actorUserId:actor,action,entityType:'offer',entityId:id,metadata}); }
function getOfferRaw(org:string,id:string):any { return sqlite.prepare(`SELECT o.*,a.candidate_id,a.requisition_id,a.status application_status,c.first_name,c.last_name,c.email,j.requisition_code,j.title,j.status job_status,j.location,j.employment_type FROM offers o JOIN applications a ON a.organization_id=o.organization_id AND a.id=o.application_id JOIN candidates c ON c.organization_id=a.organization_id AND c.id=a.candidate_id JOIN job_requisitions j ON j.organization_id=a.organization_id AND j.id=a.requisition_id WHERE o.organization_id=? AND o.id=?`).get(org,id); }
function assertOffer(org:string,id:string):any { const r=getOfferRaw(org,id); if(!r) throw new Error('Offer not found.'); return r; }
function ensureApplicationEligible(a:any) { if(a.status!=='evaluation') throw new Error('Only applications in evaluation can receive an offer. Complete the hiring decision first.'); if(a.job_status!=='open') throw new Error('The associated job requisition is not open.'); }

export function createOfferInTransaction(input:{organizationId:string;actorUserId:string;applicationId:string;currency:string;baseSalaryMinor:string|number;payFrequency:string;variableCompMinor?:string|number;joiningBonusMinor?:string|number;allowancesMinor?:string|number;otherCompMinor?:string|number;benefitsSummary?:string;employmentTerms?:string;proposedJoiningDate?:string;expiresAt?:string}):string {
  assertActiveOrg(input.organizationId); const terms=assertTerms(input);
  return withSqliteTransactionSync(()=>{
    const a=app(input.organizationId,input.applicationId); ensureApplicationEligible(a);
    if(sqlite.prepare("SELECT id FROM offers WHERE organization_id=? AND application_id=? AND status IN ('draft','pending_approval','approved','sent') LIMIT 1").get(input.organizationId,input.applicationId)) throw new Error('This application already has an active offer. Withdraw or replace it before creating another.');
    const id=nanoid(), ref=nextReference();
    sqlite.prepare(`INSERT INTO offers (id,organization_id,application_id,offer_reference,version,status,created_by,currency,base_salary_minor,pay_frequency,variable_comp_minor,joining_bonus_minor,allowances_minor,other_comp_minor,benefits_summary,employment_terms,proposed_joining_date,expires_at) VALUES (?,?,?,?,1,'draft',?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,input.organizationId,input.applicationId,ref,input.actorUserId,terms.currency,terms.baseSalaryMinor,terms.payFrequency,terms.variableCompMinor,terms.joiningBonusMinor,terms.allowancesMinor,terms.otherCompMinor,terms.benefitsSummary,terms.employmentTerms,terms.proposedJoiningDate,terms.expiresAt);
    history(input.organizationId,id,'created',null,'draft',input.actorUserId); audit(input.organizationId,input.actorUserId,'offer_created',id,{applicationId:input.applicationId,version:1});
    transitionApplicationInTx(input.organizationId,input.actorUserId,input.applicationId,'offer','Offer created');
    return id;
  });
}

export function updateDraftOfferInTransaction(input:{organizationId:string;actorUserId:string;offerId:string;currency:string;baseSalaryMinor:string|number;payFrequency:string;variableCompMinor?:string|number;joiningBonusMinor?:string|number;allowancesMinor?:string|number;otherCompMinor?:string|number;benefitsSummary?:string;employmentTerms?:string;proposedJoiningDate?:string;expiresAt?:string}):void {
  assertActiveOrg(input.organizationId); const terms=assertTerms(input); withSqliteTransactionSync(()=>{ const o=assertOffer(input.organizationId,input.offerId); if(o.status!=='draft') throw new Error('Only draft offers can be edited. Create a revision for an approved or sent offer.'); sqlite.prepare(`UPDATE offers SET currency=?,base_salary_minor=?,pay_frequency=?,variable_comp_minor=?,joining_bonus_minor=?,allowances_minor=?,other_comp_minor=?,benefits_summary=?,employment_terms=?,proposed_joining_date=?,expires_at=?,updated_at=? WHERE organization_id=? AND id=? AND status='draft'`).run(terms.currency,terms.baseSalaryMinor,terms.payFrequency,terms.variableCompMinor,terms.joiningBonusMinor,terms.allowancesMinor,terms.otherCompMinor,terms.benefitsSummary,terms.employmentTerms,terms.proposedJoiningDate,terms.expiresAt,new Date().toISOString(),input.organizationId,input.offerId); history(input.organizationId,input.offerId,'draft_updated','draft','draft',input.actorUserId); audit(input.organizationId,input.actorUserId,'offer_draft_updated',input.offerId); }); }

export function submitOfferForApprovalInTransaction(org:string,actor:string,id:string):void { assertActiveOrg(org); withSqliteTransactionSync(()=>{ const o=assertOffer(org,id); if(o.status!=='draft') throw new Error('Only draft offers can be submitted for approval.'); if(o.created_by===actor) { /* creator may submit; approval is separated below */ } sqlite.prepare("UPDATE offers SET status='pending_approval',updated_at=? WHERE organization_id=? AND id=? AND status='draft'").run(new Date().toISOString(),org,id); history(org,id,'submitted_for_approval','draft','pending_approval',actor); audit(org,actor,'offer_submitted_for_approval',id); }); }

export function approveOfferInTransaction(org:string,actor:string,id:string):void { assertActiveOrg(org); withSqliteTransactionSync(()=>{ const o=assertOffer(org,id); if(o.status!=='pending_approval') throw new Error('Only offers pending approval can be approved.'); if(o.created_by===actor) throw new Error('Offer creators cannot approve their own offers.'); const u=sqlite.prepare("SELECT id FROM users WHERE organization_id=? AND id=? AND is_active=1 AND role IN ('admin','hr')").get(org,actor); if(!u) throw new Error('Only an active HR/Admin user can approve offers.'); const now=new Date().toISOString(); sqlite.prepare("UPDATE offers SET status='approved',approved_by=?,approved_at=?,updated_at=? WHERE organization_id=? AND id=? AND status='pending_approval'").run(actor,now,now,org,id); history(org,id,'approved','pending_approval','approved',actor); audit(org,actor,'offer_approved',id); }); }

export function rejectOfferInTransaction(org:string,actor:string,id:string,reason:string):void { assertActiveOrg(org); const why=text(reason,'Rejection reason',2000,true)!; withSqliteTransactionSync(()=>{ const o=assertOffer(org,id); if(o.status!=='pending_approval') throw new Error('Only offers pending approval can be rejected.'); if(o.created_by===actor) throw new Error('Offer creators cannot reject their own offers.'); const u=sqlite.prepare("SELECT id FROM users WHERE organization_id=? AND id=? AND is_active=1 AND role IN ('admin','hr')").get(org,actor); if(!u) throw new Error('Only an active HR/Admin user can reject offers.'); sqlite.prepare("UPDATE offers SET status='rejected',approved_by=NULL,approved_at=NULL,rejection_reason=?,updated_at=? WHERE organization_id=? AND id=? AND status='pending_approval'").run(why,new Date().toISOString(),org,id); history(org,id,'rejected','pending_approval','rejected',actor,{reasonLength:why.length}); audit(org,actor,'offer_rejected',id,{reasonLength:why.length}); }); }

export function replaceOfferInTransaction(org:string,actor:string,id:string):string { assertActiveOrg(org); return withSqliteTransactionSync(()=>{ const old=assertOffer(org,id); if(!['rejected','approved','sent','withdrawn'].includes(old.status)) throw new Error('Only rejected, approved, sent, or withdrawn offers can be replaced.'); if(old.status==='sent' && old.candidate_response_token_hash) sqlite.prepare("UPDATE offers SET candidate_response_token_revoked_at=current_timestamp,updated_at=current_timestamp WHERE organization_id=? AND id=?").run(org,id); sqlite.prepare("UPDATE offers SET status='replaced',updated_at=? WHERE organization_id=? AND id=?").run(new Date().toISOString(),org,id); history(org,id,'replaced',old.status,'replaced',actor); audit(org,actor,'offer_replaced',id); const newId=nanoid(), ref=nextReference(); const fields=['application_id','version','created_by','currency','base_salary_minor','pay_frequency','variable_comp_minor','joining_bonus_minor','allowances_minor','other_comp_minor','benefits_summary','employment_terms','proposed_joining_date','expires_at']; sqlite.prepare(`INSERT INTO offers (id,organization_id,application_id,offer_reference,version,status,supersedes_offer_id,created_by,currency,base_salary_minor,pay_frequency,variable_comp_minor,joining_bonus_minor,allowances_minor,other_comp_minor,benefits_summary,employment_terms,proposed_joining_date,expires_at) SELECT ?,organization_id,application_id,?,version+1,'draft',id,?,currency,base_salary_minor,pay_frequency,variable_comp_minor,joining_bonus_minor,allowances_minor,other_comp_minor,benefits_summary,employment_terms,proposed_joining_date,expires_at FROM offers WHERE organization_id=? AND id=?`).run(newId,ref,actor,org,id); history(org,newId,'created_revision',null,'draft',actor,{supersedesOfferId:id}); audit(org,actor,'offer_revision_created',newId,{supersedesOfferId:id}); return newId; }); }

export function sendOfferInTransaction(org:string,actor:string,id:string):{responseToken:string;documentRequired:boolean} { assertActiveOrg(org); return withSqliteTransactionSync(()=>{ const o=assertOffer(org,id); if(o.status!=='approved') throw new Error('Only approved offers can be sent.'); if(o.expires_at && new Date(o.expires_at).getTime()<=Date.now()) throw new Error('The offer has expired and cannot be sent.'); if(['rejected','withdrawn','archived'].includes(o.application_status)) throw new Error('The application is no longer eligible.'); const token=generateResponseToken(), now=new Date().toISOString(), tokenExpiry=new Date(Date.now()+RESPONSE_TOKEN_TTL_MS).toISOString(); sqlite.prepare("UPDATE offers SET status='sent',sent_at=?,candidate_response_token_hash=?,candidate_response_token_expires_at=?,candidate_response_token_revoked_at=NULL,candidate_response_token_used_at=NULL,updated_at=? WHERE organization_id=? AND id=? AND status='approved'").run(now,hashResponseToken(token),tokenExpiry,now,org,id); history(org,id,'sent','approved','sent',actor); audit(org,actor,'offer_sent',id,{responseTokenIssued:true,responseTokenExpiresAt:tokenExpiry}); return {responseToken:token,documentRequired:false}; }); }

export function withdrawOfferInTransaction(org:string,actor:string,id:string):void { assertActiveOrg(org); withSqliteTransactionSync(()=>{ const o=assertOffer(org,id); if(!['approved','sent'].includes(o.status)) throw new Error('Only approved or sent offers can be withdrawn.'); sqlite.prepare("UPDATE offers SET status='withdrawn',candidate_response_token_revoked_at=CASE WHEN status='sent' THEN current_timestamp ELSE candidate_response_token_revoked_at END,updated_at=? WHERE organization_id=? AND id=? AND status=?").run(new Date().toISOString(),org,id,o.status); history(org,id,'withdrawn',o.status,'withdrawn',actor); audit(org,actor,'offer_withdrawn',id); }); }

export function expireOfferIfNeeded(org:string,id:string):boolean { return withSqliteTransactionSync(()=>{ const o=getOfferRaw(org,id); if(!o || o.status!=='sent' || !o.expires_at || new Date(o.expires_at).getTime()>Date.now()) return false; sqlite.prepare("UPDATE offers SET status='expired',candidate_response_token_revoked_at=current_timestamp,updated_at=current_timestamp WHERE organization_id=? AND id=? AND status='sent' AND expires_at IS NOT NULL AND expires_at <= ?").run(org,id,new Date().toISOString()); const n=sqlite.prepare('SELECT changes() n').get() as any; if(Number(n?.n)!==1) return false; history(org,id,'expired','sent','expired',null); audit(org,null,'offer_expired',id); return true; }); }

function responseRateKey(org:string, offerId:string, clientKey:string):string { const secret=process.env.SESSION_SECRET; if(!secret || secret.length<32) throw new Error('Response security is not configured.'); return createHmac('sha256',secret).update(`${org}:${offerId}:${clientKey}`).digest('hex'); }
function enforceResponseRateLimit(org:string,offerId:string,clientKey:string):void { const now=Date.now(); const key=responseRateKey(org,offerId,clientKey); const row=sqlite.prepare('SELECT request_count,window_started_at FROM offer_response_rate_limits WHERE key=?').get(key) as any; if(!row){ sqlite.prepare('INSERT INTO offer_response_rate_limits (key,organization_id,offer_id,request_count,window_started_at) VALUES (?,?,?,?,?)').run(key,org,offerId,1,new Date(now).toISOString()); return; } const start=new Date(row.window_started_at).getTime(); if(!Number.isFinite(start) || now-start>=RESPONSE_WINDOW_MS){ sqlite.prepare('UPDATE offer_response_rate_limits SET request_count=1,window_started_at=?,updated_at=current_timestamp WHERE key=?').run(new Date(now).toISOString(),key); return; } if(Number(row.request_count)>=RESPONSE_MAX_ATTEMPTS) throw new Error('Too many response attempts. Please try again later.'); sqlite.prepare('UPDATE offer_response_rate_limits SET request_count=request_count+1,updated_at=current_timestamp WHERE key=?').run(key); }

export function respondToOfferInTransaction(input:{token:string;decision:'accept'|'decline';reason?:string;clientKey?:string}):{ok:true;offerId:string;status:'accepted'|'declined'} { if(!/^[A-Za-z0-9_-]{43}$/.test(input.token)) throw new Error('Offer response is invalid or unavailable.'); const hash=hashResponseToken(input.token); const reason=input.decision==='decline'?text(input.reason,'Decline reason',2000,false):null; return withSqliteTransactionSync(()=>{ const o=sqlite.prepare(`SELECT o.*,a.candidate_id,g.status organization_status FROM offers o JOIN applications a ON a.organization_id=o.organization_id AND a.id=o.application_id JOIN organizations g ON g.id=o.organization_id WHERE o.candidate_response_token_hash=? LIMIT 1`).get(hash) as any; if(!o || o.organization_status!=='active') throw new Error('Offer response is invalid or unavailable.'); enforceResponseRateLimit(o.organization_id,o.id,input.clientKey?.slice(0,200)||'unknown'); if(o.status!=='sent') throw new Error('This offer is no longer available for response.'); if(o.candidate_response_token_revoked_at || o.candidate_response_token_used_at || (o.candidate_response_token_expires_at && new Date(o.candidate_response_token_expires_at).getTime()<=Date.now())) { if(o.candidate_response_token_expires_at && new Date(o.candidate_response_token_expires_at).getTime()<=Date.now()) { sqlite.prepare("UPDATE offers SET status='expired',candidate_response_token_revoked_at=current_timestamp,updated_at=current_timestamp WHERE organization_id=? AND id=? AND status='sent'").run(o.organization_id,o.id); history(o.organization_id,o.id,'expired','sent','expired',null); audit(o.organization_id,null,'offer_expired',o.id); } throw new Error('This offer is no longer available for response.'); }
    if(o.expires_at && new Date(o.expires_at).getTime()<=Date.now()){ sqlite.prepare("UPDATE offers SET status='expired',candidate_response_token_revoked_at=current_timestamp,updated_at=current_timestamp WHERE organization_id=? AND id=? AND status='sent'").run(o.organization_id,o.id); history(o.organization_id,o.id,'expired','sent','expired',null); audit(o.organization_id,null,'offer_expired',o.id); throw new Error('This offer has expired.'); }
    const next=input.decision==='accept'?'accepted':'declined'; const now=new Date().toISOString(); const result=sqlite.prepare(`UPDATE offers SET status=?,responded_at=?,response_reason=?,candidate_response_token_used_at=?,candidate_response_token_revoked_at=?,updated_at=? WHERE organization_id=? AND id=? AND status='sent' AND candidate_response_token_hash=? AND candidate_response_token_used_at IS NULL`).run(next,now,reason,now,now,now,o.organization_id,o.id,hash); if(Number(result.changes)!==1) throw new Error('Offer response could not be completed.'); history(o.organization_id,o.id,next==='accepted'?'accepted':'declined','sent',next,null,{reasonProvided:Boolean(reason)}); audit(o.organization_id,null,next==='accepted'?'offer_accepted':'offer_declined',o.id,{reasonProvided:Boolean(reason)}); if(next==='accepted') transitionApplicationInTx(o.organization_id,o.created_by,o.application_id,'hired','Offer accepted; ready for onboarding.'); return {ok:true,offerId:o.id,status:next}; }); }

export async function generateOfferLetter(org:string,actor:string,offerId:string):Promise<{ok:boolean;documentId?:string;error?:string}> {
  assertActiveOrg(org); const o=getOfferRaw(org,offerId); if(!o) return {ok:false,error:'Offer not found.'}; if(!['approved','sent','accepted','declined','expired','withdrawn'].includes(o.status)) return {ok:false,error:'Only approved or delivered offers can have an offer letter generated.'};
  const total=(Number(o.base_salary_minor)+Number(o.variable_comp_minor)+Number(o.joining_bonus_minor)+Number(o.allowances_minor)+Number(o.other_comp_minor));
  const body=[`SYJ-HCM OFFER LETTER`,`Offer reference: ${o.offer_reference}`,`Version: ${o.version}`,`Candidate: ${o.first_name} ${o.last_name}`,`Position: ${o.title}`,`Location: ${o.location||'Not specified'}`,`Currency: ${o.currency}`,`Base salary (minor units): ${o.base_salary_minor}`,`Pay frequency: ${o.pay_frequency}`,`Variable compensation (minor units): ${o.variable_comp_minor}`,`Joining bonus (minor units): ${o.joining_bonus_minor}`,`Allowances (minor units): ${o.allowances_minor}`,`Other compensation (minor units): ${o.other_comp_minor}`,`Total package components (minor units): ${total}`,`Proposed joining date: ${o.proposed_joining_date||'Not specified'}`,`Offer expires: ${o.expires_at||'Not specified'}`,`Benefits: ${o.benefits_summary||'Not specified'}`,`Employment terms: ${o.employment_terms||'Not specified'}`,`Status: ${o.status}`].join('\n');
  const file=new File([body],`${o.offer_reference}-offer-letter.txt`,{type:'text/plain'}); const result=await uploadCandidateDocument({organizationId:org,actorUserId:actor,candidateId:o.candidate_id,applicationId:o.application_id,offerId:o.id,documentType:'other',file}); if(result.documentId) audit(org,actor,'offer_document_generated',o.id,{documentId:result.documentId,scannerAvailable:result.ok}); return result.documentId?{ok:true,documentId:result.documentId,error:result.error}:{ok:false,error:result.error||'Offer letter could not be stored.'};
}

export async function listOfferEligibleApplications(org:string){ return sqlite.prepare(`SELECT a.id,a.application_reference,c.first_name,c.last_name,c.email,j.requisition_code,j.title FROM applications a JOIN candidates c ON c.organization_id=a.organization_id AND c.id=a.candidate_id JOIN job_requisitions j ON j.organization_id=a.organization_id AND j.id=a.requisition_id WHERE a.organization_id=? AND a.status='evaluation' AND j.status='open' AND NOT EXISTS (SELECT 1 FROM offers o WHERE o.organization_id=a.organization_id AND o.application_id=a.id AND o.status IN ('draft','pending_approval','approved','sent')) ORDER BY a.updated_at DESC`).all(org) as any[]; }

export function expireOffersForTenant(org:string):number { assertActiveOrg(org); return withSqliteTransactionSync(()=>{ const rows=sqlite.prepare("SELECT id FROM offers WHERE organization_id=? AND status='sent' AND expires_at IS NOT NULL AND expires_at <= ?").all(org,new Date().toISOString()) as any[]; for(const r of rows){ sqlite.prepare("UPDATE offers SET status='expired',candidate_response_token_revoked_at=current_timestamp,updated_at=current_timestamp WHERE organization_id=? AND id=? AND status='sent'").run(org,r.id); history(org,r.id,'expired','sent','expired',null); audit(org,null,'offer_expired',r.id); } return rows.length; }); }

export async function listOffers(org:string,filters:{status?:string;q?:string;creatorId?:string;jobId?:string;candidateId?:string;fromDate?:string;toDate?:string;expiration?:string}={}) { const conditions=[eq(offers.organizationId,org)]; if(filters.status&&OFFER_STATUSES.includes(filters.status as OfferStatus)) conditions.push(eq(offers.status,filters.status as OfferStatus)); if(filters.creatorId) conditions.push(eq(offers.createdBy,filters.creatorId)); if(filters.jobId) conditions.push(eq(jobRequisitions.id,filters.jobId)); if(filters.candidateId) conditions.push(eq(candidates.id,filters.candidateId)); if(filters.fromDate) conditions.push(gte(offers.createdAt,`${filters.fromDate} 00:00:00`)); if(filters.toDate) conditions.push(lte(offers.createdAt,`${filters.toDate} 23:59:59`)); if(filters.expiration==='expiring') conditions.push(gte(offers.expiresAt,new Date().toISOString()),lte(offers.expiresAt,new Date(Date.now()+7*86400000).toISOString())); if(filters.expiration==='expired') conditions.push(lte(offers.expiresAt,new Date().toISOString())); const rows=await db.select({offer:offers,candidateId:applications.candidateId,candidateFirstName:candidates.firstName,candidateLastName:candidates.lastName,candidateEmail:candidates.email,requisitionId:applications.requisitionId,requisitionCode:jobRequisitions.requisitionCode,jobTitle:jobRequisitions.title}).from(offers).innerJoin(applications,and(eq(offers.applicationId,applications.id),eq(offers.organizationId,applications.organizationId))).innerJoin(candidates,and(eq(applications.candidateId,candidates.id),eq(applications.organizationId,candidates.organizationId))).innerJoin(jobRequisitions,and(eq(applications.requisitionId,jobRequisitions.id),eq(applications.organizationId,jobRequisitions.organizationId))).where(and(...conditions)).orderBy(desc(offers.createdAt)); if(!filters.q) return rows.map((r:any)=>({...r.offer,first_name:r.candidateFirstName,last_name:r.candidateLastName,email:r.candidateEmail,requisition_code:r.requisitionCode,title:r.jobTitle})); const q=filters.q.toLowerCase(); return rows.filter((r:any)=>[r.offer.offerReference,r.candidateFirstName,r.candidateLastName,r.candidateEmail,r.requisitionCode,r.jobTitle].some(v=>String(v??'').toLowerCase().includes(q))).map((r:any)=>({...r.offer,first_name:r.candidateFirstName,last_name:r.candidateLastName,email:r.candidateEmail,requisition_code:r.requisitionCode,title:r.jobTitle})); }
export async function listOfferFilters(org:string){ const [creators,jobs,candidateRows]=await Promise.all([db.select({id:users.id,email:users.email}).from(users).where(and(eq(users.organizationId,org),eq(users.isActive,true))).orderBy(users.email),db.select({id:jobRequisitions.id,code:jobRequisitions.requisitionCode,title:jobRequisitions.title}).from(jobRequisitions).where(eq(jobRequisitions.organizationId,org)).orderBy(jobRequisitions.title),db.select({id:candidates.id,firstName:candidates.firstName,lastName:candidates.lastName}).from(candidates).where(eq(candidates.organizationId,org)).orderBy(candidates.lastName,candidates.firstName)]); return {creators,jobs,candidates:candidateRows}; }
export function getOffer(org:string,id:string){ const o=getOfferRaw(org,id); if(o?.status==='sent' && o.expires_at && new Date(o.expires_at).getTime()<=Date.now()){ expireOfferIfNeeded(org,id); return getOfferRaw(org,id) ?? null; } return o ?? null; }
export async function listOfferDocuments(org:string,id:string){ return db.select().from(candidateDocuments).where(and(eq(candidateDocuments.organizationId,org),eq(candidateDocuments.offerId,id))).orderBy(desc(candidateDocuments.createdAt)); }
export async function getOfferHistory(org:string,id:string){ return db.select().from(offerHistory).where(and(eq(offerHistory.organizationId,org),eq(offerHistory.offerId,id))).orderBy(desc(offerHistory.createdAt)); }
export function getCandidateOfferByToken(token:string){ if(!/^[A-Za-z0-9_-]{43}$/.test(token)) return null; const o=sqlite.prepare(`SELECT o.id,o.offer_reference,o.status,o.version,o.currency,o.base_salary_minor,o.pay_frequency,o.variable_comp_minor,o.joining_bonus_minor,o.allowances_minor,o.other_comp_minor,o.benefits_summary,o.employment_terms,o.proposed_joining_date,o.expires_at,o.sent_at,c.first_name,c.last_name,j.title,j.requisition_code,j.location FROM offers o JOIN applications a ON a.organization_id=o.organization_id AND a.id=o.application_id JOIN candidates c ON c.organization_id=a.organization_id AND c.id=a.candidate_id JOIN job_requisitions j ON j.organization_id=a.organization_id AND j.id=a.requisition_id JOIN organizations g ON g.id=o.organization_id WHERE o.candidate_response_token_hash=? AND g.status='active' LIMIT 1`).get(hashResponseToken(token)) as any; if(!o || o.status!=='sent') return null; if(o.expires_at && new Date(o.expires_at).getTime()<=Date.now()) { expireOfferIfNeeded((sqlite.prepare('SELECT organization_id FROM offers WHERE id=?').get(o.id) as any)?.organization_id,o.id); return null; } return o; }
