'use server';
import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import { requireRoleForAction } from '@/lib/auth';
import { uploadCandidateDocument } from '@/lib/documents/service';
import { createOfferInTransaction, updateDraftOfferInTransaction, submitOfferForApprovalInTransaction, approveOfferInTransaction, rejectOfferInTransaction, sendOfferInTransaction, withdrawOfferInTransaction, replaceOfferInTransaction, generateOfferLetter, getOffer } from '@/lib/offers';

type State={error:string|null;success?:string;responseToken?:string};
const ok={error:null} as State;
function text(fd:FormData,k:string){return String(fd.get(k)??'').trim();}
function optional(fd:FormData,k:string){const v=text(fd,k);return v||undefined;}
function fail(e:unknown):State{return {error:e instanceof Error?e.message:'Unable to complete the offer operation.'};}
function input(fd:FormData){return {organizationId:'',actorUserId:'',applicationId:text(fd,'applicationId'),currency:text(fd,'currency'),baseSalaryMinor:text(fd,'baseSalaryMinor'),payFrequency:text(fd,'payFrequency'),variableCompMinor:optional(fd,'variableCompMinor'),joiningBonusMinor:optional(fd,'joiningBonusMinor'),allowancesMinor:optional(fd,'allowancesMinor'),otherCompMinor:optional(fd,'otherCompMinor'),benefitsSummary:optional(fd,'benefitsSummary'),employmentTerms:optional(fd,'employmentTerms'),proposedJoiningDate:optional(fd,'proposedJoiningDate'),expiresAt:optional(fd,'expiresAt')}}
export async function createOfferAction(_prev:State,fd:FormData):Promise<State>{const a=await requireRoleForAction('admin','hr');try{const i=input(fd);const id=createOfferInTransaction({...i,organizationId:a.organizationId,actorUserId:a.id});redirect(`/recruitment/offers/${id}`);return ok;}catch(e){return fail(e)}}
export async function updateDraftOfferAction(_prev:State,fd:FormData):Promise<State>{const a=await requireRoleForAction('admin','hr');try{const i=input(fd);updateDraftOfferInTransaction({...i,offerId:text(fd,'offerId'),organizationId:a.organizationId,actorUserId:a.id});revalidatePath(`/recruitment/offers/${text(fd,'offerId')}`);return ok}catch(e){return fail(e)}}
export async function submitOfferAction(fd:FormData){const a=await requireRoleForAction('admin','hr');const id=text(fd,'offerId');try{submitOfferForApprovalInTransaction(a.organizationId,a.id,id)}catch(e){redirect(`/recruitment/offers/${id}?error=${encodeURIComponent(e instanceof Error?e.message:'Unable to submit offer.')}`)}revalidatePath(`/recruitment/offers/${id}`);revalidatePath('/recruitment/offers');redirect(`/recruitment/offers/${id}`)}
export async function approveOfferAction(fd:FormData){const a=await requireRoleForAction('admin','hr');const id=text(fd,'offerId');try{approveOfferInTransaction(a.organizationId,a.id,id)}catch(e){redirect(`/recruitment/offers/${id}?error=${encodeURIComponent(e instanceof Error?e.message:'Unable to approve offer.')}`)}revalidatePath(`/recruitment/offers/${id}`);revalidatePath('/recruitment/offers');redirect(`/recruitment/offers/${id}`)}
export async function rejectOfferAction(fd:FormData){const a=await requireRoleForAction('admin','hr');const id=text(fd,'offerId');try{rejectOfferInTransaction(a.organizationId,a.id,id,text(fd,'reason'))}catch(e){redirect(`/recruitment/offers/${id}?error=${encodeURIComponent(e instanceof Error?e.message:'Unable to reject offer.')}`)}revalidatePath(`/recruitment/offers/${id}`);revalidatePath('/recruitment/offers');redirect(`/recruitment/offers/${id}`)}
export async function sendOfferAction(fd:FormData){const a=await requireRoleForAction('admin','hr');const id=text(fd,'offerId');try{const r=sendOfferInTransaction(a.organizationId,a.id,id);revalidatePath(`/recruitment/offers/${id}`);revalidatePath('/recruitment/offers');redirect(`/recruitment/offers/${id}?response_token=${encodeURIComponent(r.responseToken)}`)}catch(e){redirect(`/recruitment/offers/${id}?error=${encodeURIComponent(e instanceof Error?e.message:'Unable to send offer.')}`)}}
export async function withdrawOfferAction(fd:FormData){const a=await requireRoleForAction('admin','hr');const id=text(fd,'offerId');try{withdrawOfferInTransaction(a.organizationId,a.id,id)}catch(e){redirect(`/recruitment/offers/${id}?error=${encodeURIComponent(e instanceof Error?e.message:'Unable to withdraw offer.')}`)}revalidatePath(`/recruitment/offers/${id}`);revalidatePath('/recruitment/offers');redirect(`/recruitment/offers/${id}`)}
export async function reviseOfferAction(fd:FormData){const a=await requireRoleForAction('admin','hr');const id=text(fd,'offerId');try{const newId=replaceOfferInTransaction(a.organizationId,a.id,id);revalidatePath(`/recruitment/offers/${id}`);revalidatePath('/recruitment/offers');redirect(`/recruitment/offers/${newId}`)}catch(e){redirect(`/recruitment/offers/${id}?error=${encodeURIComponent(e instanceof Error?e.message:'Unable to create revision.')}`)}}
export async function generateOfferLetterAction(fd:FormData){const a=await requireRoleForAction('admin','hr');const id=text(fd,'offerId');try{const r=await generateOfferLetter(a.organizationId,a.id,id);if(!r.ok) throw new Error(r.error||'Unable to generate offer letter.')}catch(e){redirect(`/recruitment/offers/${id}?error=${encodeURIComponent(e instanceof Error?e.message:'Unable to generate offer letter.')}`)}revalidatePath(`/recruitment/offers/${id}`);redirect(`/recruitment/offers/${id}`)}

export async function uploadOfferDocumentAction(_prev:State,fd:FormData):Promise<State>{const a=await requireRoleForAction('admin','hr');const id=text(fd,'offerId');const offer=getOffer(a.organizationId,id);if(!offer)return {error:'Offer not found.'};const file=fd.get('file');if(!(file instanceof File))return {error:'Select a valid document.'};const r=await uploadCandidateDocument({organizationId:a.organizationId,actorUserId:a.id,candidateId:offer.candidate_id,applicationId:offer.application_id,offerId:id,documentType:'other',file});revalidatePath(`/recruitment/offers/${id}`);return r.documentId?{error:null,success:r.ok?'Document uploaded and validated.':`Document stored with scanner status pending/unavailable (${r.error||'not clean'}).`}:{error:r.error||'Document upload failed.'};}
