'use client';
import { useFormState, useFormStatus } from 'react-dom';
import { changeWorkflowStageAction, createNoteAction, createInterviewAction, rescheduleInterviewAction, assignParticipantAction, submitFeedbackAction, correctFeedbackAction, recordDecisionAction, updateStageAction } from './workflow-actions';
import { DECISION_OUTCOMES, FEEDBACK_RECOMMENDATIONS, INTERVIEW_TYPES } from '@/lib/recruitment-constants';

const initial={error:null};
function Submit({children}:{children:string}){const {pending}=useFormStatus();return <button className="btn-primary" disabled={pending}>{pending?'Saving…':children}</button>}
function ErrorText({error}:{error:string|null}){return error?<p className="text-sm text-red-600" role="alert">{error}</p>:null}

export function StageTransitionForm({applicationId,status,nextStatuses}:{applicationId:string;status:string;nextStatuses:string[]}){const [state,action]=useFormState(changeWorkflowStageAction,initial);return <form action={action} className="card p-5 space-y-4"><input type="hidden" name="applicationId" value={applicationId}/><div><label className="label">Move application to</label><select className="input" name="status" defaultValue={nextStatuses[0]||''} disabled={nextStatuses.length===0}>{nextStatuses.map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select><p className="mt-1 text-xs text-surface-500">Server-side transition rules still apply; invalid moves are rejected.</p></div><div><label className="label">Reason</label><input className="input" name="reason" required maxLength={1000} placeholder={`Why move from ${status}?`}/></div><ErrorText error={state.error}/><Submit>Change stage</Submit></form>}

export function NoteForm({candidateId,applicationId}:{candidateId:string;applicationId?:string}){const [state,action]=useFormState(createNoteAction,initial);return <form action={action} className="space-y-3"><input type="hidden" name="candidateId" value={candidateId}/>{applicationId&&<input type="hidden" name="applicationId" value={applicationId}/>}<textarea className="input" name="content" rows={4} maxLength={10000} required placeholder="Internal recruitment note…"/><ErrorText error={state.error}/><Submit>Add note</Submit></form>}

export function InterviewForm({applications,people,rounds,defaultTimezone,defaultApplicationId}:{applications:any[];people:any[];rounds:any[];defaultTimezone:string;defaultApplicationId?:string}){const [state,action]=useFormState(createInterviewAction,initial);return <form action={action} className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><label className="label">Application *</label><select className="input" name="applicationId" required defaultValue={defaultApplicationId||""}><option value="" disabled>Select application</option>{applications.map(a=><option key={a.id} value={a.id}>{a.application_reference} — {a.first_name} {a.last_name} — {a.job_title}</option>)}</select></div><div><label className="label">Round name</label><input className="input" name="roundName" maxLength={120} placeholder="Technical interview"/></div><div><label className="label">Title *</label><input className="input" name="title" maxLength={200} required placeholder="Technical interview"/></div><div><label className="label">Interview type *</label><select className="input" name="interviewType" defaultValue="technical">{INTERVIEW_TYPES.map(t=><option key={t} value={t}>{t.replaceAll('_',' ')}</option>)}</select></div><div><label className="label">Timezone *</label><input className="input" name="timezone" defaultValue={defaultTimezone} maxLength={80} required/></div><div><label className="label">Start *</label><input className="input" type="datetime-local" name="startLocal" required/></div><div><label className="label">End *</label><input className="input" type="datetime-local" name="endLocal" required/></div><div><label className="label">Location</label><input className="input" name="location" maxLength={500} placeholder="Office / Remote"/></div><div><label className="label">Meeting details</label><input className="input" name="meetingDetails" maxLength={2000} placeholder="Meeting link or instructions"/></div><div className="sm:col-span-2"><label className="label">Interviewers *</label><select className="input min-h-32" name="participantIds" multiple required>{people.map(p=><option key={p.id} value={p.id}>{p.first_name||''} {p.last_name||''} — {p.email}</option>)}</select><p className="mt-1 text-xs text-surface-500">Use Ctrl/Command to select multiple interviewers. Every selected user must belong to this organization.</p></div></div><ErrorText error={state.error}/><Submit>Schedule interview</Submit></form>}

export function RescheduleForm({interviewId,timezone,startLocal,endLocal}:{interviewId:string;timezone:string;startLocal:string;endLocal:string}){const [state,action]=useFormState(rescheduleInterviewAction,initial);return <form action={action} className="card p-5 space-y-4"><input type="hidden" name="interviewId" value={interviewId}/><div className="grid gap-4 sm:grid-cols-3"><div><label className="label">Start</label><input className="input" type="datetime-local" name="startLocal" defaultValue={startLocal}/></div><div><label className="label">End</label><input className="input" type="datetime-local" name="endLocal" defaultValue={endLocal}/></div><div><label className="label">Timezone</label><input className="input" name="timezone" defaultValue={timezone}/></div></div><ErrorText error={state.error}/><Submit>Reschedule</Submit></form>}

export function ParticipantForm({interviewId,people}:{interviewId:string;people:any[]}){const [state,action]=useFormState(assignParticipantAction,initial);return <form action={action} className="flex flex-wrap gap-3 items-end"><input type="hidden" name="interviewId" value={interviewId}/><div className="min-w-64 flex-1"><label className="label">Add interviewer</label><select className="input" name="userId" required defaultValue=""><option value="" disabled>Select user</option>{people.map(p=><option key={p.id} value={p.id}>{p.first_name||''} {p.last_name||''} — {p.email}</option>)}</select></div><Submit>Add interviewer</Submit><ErrorText error={state.error}/></form>}

export function FeedbackForm({interviewId}:{interviewId:string}){const [state,action]=useFormState(submitFeedbackAction,initial);return <form action={action} className="space-y-4"><input type="hidden" name="interviewId" value={interviewId}/><div className="grid gap-4 sm:grid-cols-2"><div><label className="label">Score *</label><input className="input" name="score" type="number" min="1" max="5" required/></div><div><label className="label">Recommendation *</label><select className="input" name="recommendation" defaultValue="neutral">{FEEDBACK_RECOMMENDATIONS.map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</select></div><div className="sm:col-span-2"><label className="label">Strengths *</label><textarea className="input" name="strengths" rows={3} maxLength={5000} required/></div><div className="sm:col-span-2"><label className="label">Concerns *</label><textarea className="input" name="concerns" rows={3} maxLength={5000} required/></div><div className="sm:col-span-2"><label className="label">Notes</label><textarea className="input" name="notes" rows={3} maxLength={5000}/></div></div><ErrorText error={state.error}/><Submit>Submit feedback</Submit></form>}

export function FeedbackCorrectionForm({feedback,interviewId}:{feedback:any;interviewId:string}){const latest=feedback;const [state,action]=useFormState(correctFeedbackAction,initial);return <form action={action} className="mt-4 space-y-4 rounded-lg border border-amber-200 bg-amber-50 p-4"><input type="hidden" name="feedbackId" value={feedback.id}/><input type="hidden" name="interviewId" value={interviewId}/><div className="grid gap-4 sm:grid-cols-2"><div><label className="label">Corrected score</label><input className="input" type="number" min="1" max="5" name="score" defaultValue={latest.score}/></div><div><label className="label">Recommendation</label><select className="input" name="recommendation" defaultValue={latest.recommendation}>{FEEDBACK_RECOMMENDATIONS.map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</select></div><div className="sm:col-span-2"><label className="label">Strengths</label><textarea className="input" name="strengths" defaultValue={latest.strengths} maxLength={5000}/></div><div className="sm:col-span-2"><label className="label">Concerns</label><textarea className="input" name="concerns" defaultValue={latest.concerns} maxLength={5000}/></div><div className="sm:col-span-2"><label className="label">Notes</label><textarea className="input" name="notes" defaultValue={latest.notes||''} maxLength={5000}/></div><div className="sm:col-span-2"><label className="label">Correction reason *</label><input className="input" name="reason" maxLength={1000} required/></div></div><ErrorText error={state.error}/><Submit>Record correction</Submit></form>}

export function DecisionForm({interviewId}:{interviewId:string}){const [state,action]=useFormState(recordDecisionAction,initial);return <form action={action} className="space-y-4"><input type="hidden" name="interviewId" value={interviewId}/><div><label className="label">Decision *</label><select className="input" name="outcome" defaultValue="advance">{DECISION_OUTCOMES.map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</select></div><div><label className="label">Rationale *</label><textarea className="input" name="rationale" rows={4} maxLength={5000} required/></div><ErrorText error={state.error}/><Submit>Record decision</Submit></form>}

export function StageSettings({stages}:{stages:any[]}){return <div className="space-y-3">{stages.map(s=><StageRow key={s.id} stage={s}/>)}</div>}
function StageRow({stage}:{stage:any}){const [state,action]=useFormState(updateStageAction,initial);return <form action={action} className="grid gap-3 rounded-lg border border-surface-200 p-4 sm:grid-cols-[1fr_110px_120px_auto] items-end"><input type="hidden" name="stageId" value={stage.id}/><div><label className="label">Stage name</label><input className="input" name="name" defaultValue={stage.name} maxLength={100} required/></div><div><label className="label">Order</label><input className="input" name="position" type="number" min="0" max="99" defaultValue={stage.position} required/></div><div><label className="label">Active</label><select className="input" name="isActive" defaultValue={stage.isActive?'true':'false'}><option value="true">Active</option><option value="false">Inactive</option></select></div><Submit>Save</Submit>{state.error&&<div className="sm:col-span-4"><ErrorText error={state.error}/></div>}</form>}
