import { test } from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const dbPath=path.join(os.tmpdir(),`syj-hcm-phase24-${process.pid}-${Date.now()}.db`);
const sqlite=new DatabaseSync(dbPath);
sqlite.exec('PRAGMA foreign_keys=ON');
for(const file of fs.readdirSync(path.resolve(process.cwd(),'drizzle')).filter(f=>f.endsWith('.sql')).sort()) sqlite.exec(fs.readFileSync(path.resolve(process.cwd(),'drizzle',file),'utf8'));
sqlite.exec(`CREATE TABLE IF NOT EXISTS __migrations_test (name TEXT PRIMARY KEY)`);

function reset() {
  sqlite.exec("DELETE FROM public_application_rate_limits; DELETE FROM candidate_documents; DELETE FROM candidate_activities; DELETE FROM candidate_notes; DELETE FROM application_history; DELETE FROM job_publications; DELETE FROM applications; DELETE FROM candidates; DELETE FROM job_requisitions; DELETE FROM departments; DELETE FROM users WHERE id IN ('pub-a','pub-b'); DELETE FROM employees; DELETE FROM organization_settings WHERE organization_id IN ('pub_org_a','pub_org_b'); DELETE FROM organizations WHERE id IN ('pub_org_a','pub_org_b');");
  sqlite.prepare("INSERT OR IGNORE INTO organizations (id,name,slug,status) VALUES ('pub_org_a','Public A','public-a','active'),('pub_org_b','Public B','public-b','active')").run();
  sqlite.prepare("INSERT OR IGNORE INTO organization_settings (organization_id,public_careers_enabled) VALUES ('pub_org_a',1),('pub_org_b',1)").run();
  sqlite.prepare("UPDATE organization_settings SET public_careers_enabled=1 WHERE organization_id IN ('pub_org_a','pub_org_b')").run();
  sqlite.prepare("INSERT OR IGNORE INTO users (id,organization_id,email,password_hash,password_salt,role) VALUES ('pub-a','pub_org_a','pub-a@test','x','x','hr'),('pub-b','pub_org_b','pub-b@test','x','x','hr')").run();
  sqlite.prepare("INSERT INTO job_requisitions (id,organization_id,requisition_code,title,employment_type,description,requirements,status,created_by) VALUES ('pub-job-a','pub_org_a','PUB-A','Backend Engineer','full_time','Public backend role','Experience','open','pub-a'),('pub-job-b','pub_org_b','PUB-B','Other Backend Role','full_time','Other role','Experience','open','pub-b')").run();
}
function publication(id='pub-p-a',org='pub_org_a',job='pub-job-a',slug='backend-engineer-a',status='draft') {
  sqlite.prepare("INSERT INTO job_publications (id,organization_id,job_requisition_id,public_slug,public_title,public_description,public_location,employment_type,workplace_type,status,application_enabled,created_by) VALUES (?,?,?,?,?,?,?,?,? ,?,1,?)").run(id,org,job,slug,'Backend Engineer','A public role','Hyderabad','full_time','hybrid',status,org==='pub_org_a'?'pub-a':'pub-b');
}

test('publication table exists',()=>{assert.ok(sqlite.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name='job_publications'").get())});
test('rate limit table exists',()=>{assert.ok(sqlite.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name='public_application_rate_limits'").get())});
test('organization public careers defaults off for new settings',()=>{sqlite.prepare("INSERT INTO organizations (id,name,slug,status) VALUES ('pub_org_new','New','new-public','active')").run();sqlite.prepare("INSERT INTO organization_settings (organization_id) VALUES ('pub_org_new')").run();const r=sqlite.prepare("SELECT public_careers_enabled FROM organization_settings WHERE organization_id='pub_org_new'").get() as any;assert.equal(r.public_careers_enabled,0);sqlite.prepare("DELETE FROM organization_settings WHERE organization_id='pub_org_new'").run();sqlite.prepare("DELETE FROM organizations WHERE id='pub_org_new'").run()});
test('publication requires tenant-local requisition',()=>{reset();assert.throws(()=>publication('x','pub_org_a','pub-job-b','cross-job'),'FOREIGN KEY')});
test('publication requires tenant-local creator',()=>{reset();assert.throws(()=>sqlite.prepare("INSERT INTO job_publications (id,organization_id,job_requisition_id,public_slug,public_title,public_description,employment_type,workplace_type,created_by) VALUES ('x','pub_org_a','pub-job-a','cross-creator','x','x','full_time','remote','pub-b')").run(),/FOREIGN KEY/)});
test('public slug is globally unique',()=>{reset();publication();assert.throws(()=>publication('pub-p-b','pub_org_b','pub-job-b','backend-engineer-a','draft'),/UNIQUE/)});
test('same tenant cannot publish two representations of one requisition',()=>{reset();publication();assert.throws(()=>publication('pub-p-2','pub_org_a','pub-job-a','backend-engineer-2','draft'),/UNIQUE/)});
test('invalid publication status is rejected',()=>{reset();assert.throws(()=>publication('x','pub_org_a','pub-job-a','x-invalid','invalid'),/CHECK/)});
test('invalid workplace type is rejected',()=>{reset();assert.throws(()=>sqlite.prepare("INSERT INTO job_publications (id,organization_id,job_requisition_id,public_slug,public_title,public_description,employment_type,workplace_type,created_by) VALUES ('x','pub_org_a','pub-job-a','workplace-invalid','x','x','full_time','everywhere','pub-a')").run(),/CHECK/)});
test('publish guard rejects empty public title',()=>{reset();publication();assert.throws(()=>sqlite.prepare("UPDATE job_publications SET status='published',public_title='' WHERE id='pub-p-a'").run(),/publication is not valid/i)});
test('publish guard rejects malformed slug',()=>{reset();publication();assert.throws(()=>sqlite.prepare("UPDATE job_publications SET status='published',public_slug='../bad' WHERE id='pub-p-a'").run(),/publication is not valid/i)});
test('published publication stores no internal requisition fields beyond relationship',()=>{reset();publication();const cols=sqlite.prepare('PRAGMA table_info(job_publications)').all().map((r:any)=>r.name);assert.equal(cols.includes('salary_min'),false);assert.equal(cols.includes('recruiter_user_id'),false);assert.equal(cols.includes('hiring_manager_employee_id'),false)});
test('rate limit row is tenant bound to publication',()=>{reset();publication();sqlite.prepare("INSERT INTO public_application_rate_limits (key,organization_id,publication_id,request_count,window_started_at) VALUES ('k','pub_org_a','pub-p-a',1,current_timestamp)").run();assert.throws(()=>sqlite.prepare("INSERT INTO public_application_rate_limits (key,organization_id,publication_id,request_count,window_started_at) VALUES ('k2','pub_org_b','pub-p-a',1,current_timestamp)").run(),/FOREIGN KEY/)});
test('application candidate tenant constraint remains enforced',()=>{reset();sqlite.prepare("INSERT INTO candidates (id,organization_id,first_name,last_name,email,created_by) VALUES ('pub-c-a','pub_org_a','A','A','a@a.test','pub-a')").run();assert.throws(()=>sqlite.prepare("INSERT INTO applications (id,organization_id,candidate_id,requisition_id,application_reference) VALUES ('pub-app-x','pub_org_b','pub-c-a','pub-job-b','APP-X')").run(),/FOREIGN KEY/)});
test('application requisition tenant constraint remains enforced',()=>{reset();sqlite.prepare("INSERT INTO candidates (id,organization_id,first_name,last_name,email,created_by) VALUES ('pub-c-a','pub_org_a','A','A','a@a.test','pub-a')").run();assert.throws(()=>sqlite.prepare("INSERT INTO applications (id,organization_id,candidate_id,requisition_id,application_reference) VALUES ('pub-app-x','pub_org_a','pub-c-a','pub-job-b','APP-X')").run(),/FOREIGN KEY/)});
test('public cover letter column is bounded at application layer',()=>{const cols=sqlite.prepare('PRAGMA table_info(applications)').all().map((r:any)=>r.name);assert.ok(cols.includes('public_cover_letter'))});
test('rate request count cannot be negative',()=>{reset();publication();assert.throws(()=>sqlite.prepare("INSERT INTO public_application_rate_limits (key,organization_id,publication_id,request_count,window_started_at) VALUES ('negative','pub_org_a','pub-p-a',-1,current_timestamp)").run(),/CHECK/)});
test('publication identity cannot change',()=>{reset();publication();assert.throws(()=>sqlite.prepare("UPDATE job_publications SET organization_id='pub_org_b' WHERE id='pub-p-a'").run(),/immutable/i)});
test('archived publication is retained but not treated as published by status',()=>{reset();publication('pub-p-a','pub_org_a','pub-job-a','archived-role','archived');const r=sqlite.prepare("SELECT status FROM job_publications WHERE id='pub-p-a'").get() as any;assert.equal(r.status,'archived')});
test('closed publication is retained',()=>{reset();publication('pub-p-a','pub_org_a','pub-job-a','closed-role','closed');const r=sqlite.prepare("SELECT status FROM job_publications WHERE id='pub-p-a'").get() as any;assert.equal(r.status,'closed')});
test('application_enabled is constrained to boolean values',()=>{reset();publication();assert.throws(()=>sqlite.prepare("UPDATE job_publications SET application_enabled=2 WHERE id='pub-p-a'").run(),/CHECK/)});
test('historical migrations remain present through 0007',()=>{const files=fs.readdirSync(path.resolve(process.cwd(),'drizzle')).filter(f=>f.endsWith('.sql')).sort();assert.deepEqual(files.slice(0,8),['0000_init.sql','0001_phase1_1_security.sql','0002_attendance_clock_order_insert_guard.sql','0003_multi_tenant_foundation.sql','0004_phase1_2c_productization.sql','0005_phase2_1_recruitment_foundation.sql','0006_phase2_2_recruitment_workflow_interviews.sql','0007_phase2_3_candidate_documents.sql']);});
test('public publication does not expose raw job table as its schema',()=>{const cols=sqlite.prepare('PRAGMA table_info(job_publications)').all().map((r:any)=>r.name);for(const forbidden of ['salary_min','salary_max','currency','requirements','skills','recruiter_user_id','hiring_manager_employee_id'])assert.equal(cols.includes(forbidden),false)});
test('tenant-specific publication index exists',()=>{assert.ok(sqlite.prepare("SELECT 1 FROM sqlite_master WHERE type='index' AND name='job_publications_status_idx'").get())});
test('slug index exists',()=>{assert.ok(sqlite.prepare("SELECT 1 FROM sqlite_master WHERE type='index' AND name='job_publications_public_slug_idx'").get())});
test('public publication has no recruiter identity field',()=>{const cols=sqlite.prepare('PRAGMA table_info(job_publications)').all().map((r:any)=>r.name);assert.equal(cols.includes('recruiter_user_id'),false)});
test('public publication has no hiring manager identity field',()=>{const cols=sqlite.prepare('PRAGMA table_info(job_publications)').all().map((r:any)=>r.name);assert.equal(cols.includes('hiring_manager_employee_id'),false)});
test('public publication has no internal salary fields',()=>{const cols=sqlite.prepare('PRAGMA table_info(job_publications)').all().map((r:any)=>r.name);assert.equal(cols.includes('salary_min'),false);assert.equal(cols.includes('salary_max'),false)});
test('public publication has no internal requirements field',()=>{const cols=sqlite.prepare('PRAGMA table_info(job_publications)').all().map((r:any)=>r.name);assert.equal(cols.includes('requirements'),false)});
test('public publication application flag is stored separately from requisition status',()=>{reset();publication();const r=sqlite.prepare('SELECT application_enabled,status FROM job_publications WHERE id=?').get('pub-p-a') as any;assert.equal(r.application_enabled,1);assert.equal(r.status,'draft')});
test('suspended organizations can retain publications without deleting data',()=>{reset();publication('pub-p-a','pub_org_a','pub-job-a','suspended-role','published');sqlite.prepare("UPDATE organizations SET status='suspended' WHERE id='pub_org_a'").run();const r=sqlite.prepare("SELECT p.status FROM job_publications p JOIN organizations o ON o.id=p.organization_id WHERE p.id='pub-p-a'").get() as any;assert.equal(r.status,'published')});
test('careers-disabled organizations can retain published data without deleting data',()=>{reset();publication('pub-p-a','pub_org_a','pub-job-a','disabled-role','published');sqlite.prepare("UPDATE organization_settings SET public_careers_enabled=0 WHERE organization_id='pub_org_a'").run();const r=sqlite.prepare("SELECT public_careers_enabled FROM organization_settings WHERE organization_id='pub_org_a'").get() as any;assert.equal(r.public_careers_enabled,0)});
test('expired closing date is retained for request-time enforcement',()=>{reset();publication('pub-p-a','pub_org_a','pub-job-a','expired-role','published');sqlite.prepare("UPDATE job_publications SET closes_at=? WHERE id='pub-p-a'").run(new Date(Date.now()-60000).toISOString());const r=sqlite.prepare("SELECT status,closes_at FROM job_publications WHERE id='pub-p-a'").get() as any;assert.equal(r.status,'published');assert.ok(new Date(r.closes_at).getTime()<Date.now())});
