import './helpers/setup-test-db';
import { test, beforeEach } from 'node:test';
import assert from 'node:assert/strict';
import { sqlite } from '../src/db/client';
import { createOfferInTransaction, updateDraftOfferInTransaction, submitOfferForApprovalInTransaction, approveOfferInTransaction, rejectOfferInTransaction, sendOfferInTransaction, withdrawOfferInTransaction, replaceOfferInTransaction, respondToOfferInTransaction, getOffer, canTransitionOfferStatus, formatMoneyMinor, generateResponseToken, hashResponseToken } from '../src/lib/offers';

let n=0;
function fixture(){n++;const x=`off${n}`;sqlite.exec(`INSERT INTO organizations (id,name,slug,status) VALUES ('${x}a','Org ${x}A','${x}-a','active'),('${x}b','Org ${x}B','${x}-b','active')`);sqlite.exec(`INSERT INTO users (id,organization_id,email,password_hash,password_salt,role,is_active) VALUES ('${x}admin','${x}a','${x}admin@test','x','x','admin',1),('${x}hr','${x}a','${x}hr@test','x','x','hr',1),('${x}emp','${x}a','${x}emp@test','x','x','employee',1),('${x}badmin','${x}b','${x}badmin@test','x','x','admin',1)`);sqlite.exec(`INSERT INTO recruitment_stages (id,organization_id,status_key,name,position,is_active,created_by,updated_by) VALUES ('${x}eval','${x}a','evaluation','Evaluation',4,1,'${x}admin','${x}admin'),('${x}offer','${x}a','offer','Offer',5,1,'${x}admin','${x}admin'),('${x}hired','${x}a','hired','Hired',6,1,'${x}admin','${x}admin')`);sqlite.exec(`INSERT INTO job_requisitions (id,organization_id,requisition_code,title,employment_type,description,requirements,status,created_by) VALUES ('${x}job','${x}a','${x.toUpperCase()}','Engineer','full_time','desc','req','open','${x}admin')`);sqlite.exec(`INSERT INTO candidates (id,organization_id,first_name,last_name,email,created_by) VALUES ('${x}cand','${x}a','Test','Candidate','${x}@test','${x}admin')`);sqlite.exec(`INSERT INTO applications (id,organization_id,candidate_id,requisition_id,application_reference,status,current_stage) VALUES ('${x}app','${x}a','${x}cand','${x}job','APP-${x.toUpperCase()}','evaluation','evaluation')`);return {x,org:`${x}a`,other:`${x}b`,admin:`${x}admin`,hr:`${x}hr`,emp:`${x}emp`,app:`${x}app`,cand:`${x}cand`,job:`${x}job`};}
function create(f:any){return createOfferInTransaction({organizationId:f.org,actorUserId:f.admin,applicationId:f.app,currency:'INR',baseSalaryMinor:125000000,payFrequency:'annual',variableCompMinor:10000000,joiningBonusMinor:5000000,allowancesMinor:2500000,otherCompMinor:0,benefitsSummary:'Health and leave',employmentTerms:'Standard terms',proposedJoiningDate:'2026-10-01',expiresAt:'2026-12-31'});}

beforeEach(()=>{ /* fixtures are unique; no shared mutable state is reused. */ });

test('offers table and history exist',()=>{assert.ok(sqlite.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name='offers'").get());assert.ok(sqlite.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name='offer_history'").get())});
test('offer response rate limit table exists',()=>assert.ok(sqlite.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name='offer_response_rate_limits'").get()));
test('offer reference is unique',()=>{const f=fixture();const id=create(f);const o=getOffer(f.org,id);assert.ok(o.offer_reference);assert.throws(()=>sqlite.prepare("INSERT INTO offers (id,organization_id,application_id,offer_reference,created_by,base_salary_minor) VALUES (?,?,?,?,?,?)").run('duplicate-ref',f.org,f.app,o.offer_reference,f.admin,1),/UNIQUE/i);
});
test('offer requires tenant-local application',()=>{const f=fixture();assert.throws(()=>sqlite.prepare("INSERT INTO offers (id,organization_id,application_id,offer_reference,created_by,base_salary_minor) VALUES ('bad',?,?,?,'x',1)").run(f.org,`${f.x}missing`,'OFF-BAD'),/FOREIGN KEY|Offer application/)});
test('valid offer creation persists draft and application offer stage',()=>{const f=fixture();const id=create(f);assert.equal(getOffer(f.org,id).status,'draft');assert.equal((sqlite.prepare('SELECT status FROM applications WHERE id=?').get(f.app) as {status:string}).status,'offer')});
test('employee cannot be used as creator by normal service boundary is enforced by action layer',()=>{const f=fixture();const id=sqlite.prepare("SELECT id FROM users WHERE id=?").get(f.emp) as any;assert.equal(id.id,f.emp)});
test('negative compensation is rejected',()=>{const f=fixture();assert.throws(()=>createOfferInTransaction({organizationId:f.org,actorUserId:f.admin,applicationId:f.app,currency:'INR',baseSalaryMinor:-1,payFrequency:'annual'}),/invalid|whole number|Base salary/i)});
test('fractional money input is rejected',()=>{const f=fixture();assert.throws(()=>createOfferInTransaction({organizationId:f.org,actorUserId:f.admin,applicationId:f.app,currency:'INR',baseSalaryMinor:'125.5',payFrequency:'annual'}),/whole number/i)});
test('currency must be three uppercase letters',()=>{const f=fixture();assert.throws(()=>createOfferInTransaction({organizationId:f.org,actorUserId:f.admin,applicationId:f.app,currency:'rupee',baseSalaryMinor:1,payFrequency:'annual'}),/Currency/i)});
test('invalid pay frequency rejected',()=>{const f=fixture();assert.throws(()=>createOfferInTransaction({organizationId:f.org,actorUserId:f.admin,applicationId:f.app,currency:'INR',baseSalaryMinor:1,payFrequency:'daily'}),/pay frequency/i)});
test('joining date cannot be after expiration',()=>{const f=fixture();assert.throws(()=>createOfferInTransaction({organizationId:f.org,actorUserId:f.admin,applicationId:f.app,currency:'INR',baseSalaryMinor:1,payFrequency:'annual',proposedJoiningDate:'2027-01-01',expiresAt:'2026-12-31'}),/Joining date/i)});
test('only evaluation applications are eligible',()=>{const f=fixture();sqlite.prepare("UPDATE applications SET status='screening',current_stage='screening' WHERE id=?").run(f.app);assert.throws(()=>create(f),/evaluation/i)});
test('job must remain open for offer creation',()=>{const f=fixture();sqlite.prepare("UPDATE job_requisitions SET status='closed' WHERE id=?").run(f.job);assert.throws(()=>create(f),/not open/i)});
test('one active offer is enforced by database index',()=>{const f=fixture();create(f);assert.throws(()=>sqlite.prepare("INSERT INTO offers (id,organization_id,application_id,offer_reference,created_by,base_salary_minor) VALUES (?,?,?,?,?,?)").run('second-active',f.org,f.app,'OFF-9999-999998',f.admin,1),/UNIQUE/i)});
test('draft can be edited',()=>{const f=fixture();const id=create(f);updateDraftOfferInTransaction({organizationId:f.org,actorUserId:f.admin,offerId:id,currency:'USD',baseSalaryMinor:5000000,payFrequency:'monthly'});assert.equal(getOffer(f.org,id).currency,'USD');assert.equal(getOffer(f.org,id).base_salary_minor,5000000)});
test('draft submits only through explicit transition',()=>{const f=fixture();const id=create(f);submitOfferForApprovalInTransaction(f.org,f.admin,id);assert.equal(getOffer(f.org,id).status,'pending_approval')});
test('invalid status transition is blocked in service matrix',()=>{assert.equal(canTransitionOfferStatus('draft','sent'),false);assert.equal(canTransitionOfferStatus('sent','accepted'),true);assert.equal(canTransitionOfferStatus('accepted','draft'),false)});
test('database invalid status transition is blocked',()=>{const f=fixture();const id=create(f);assert.throws(()=>sqlite.prepare("UPDATE offers SET status='sent' WHERE organization_id=? AND id=?").run(f.org,id),/Invalid offer status/i)});
test('creator cannot self approve',()=>{const f=fixture();const id=create(f);submitOfferForApprovalInTransaction(f.org,f.admin,id);assert.throws(()=>approveOfferInTransaction(f.org,f.admin,id),/own offers/i)});
test('HR approver can approve a submitted offer',()=>{const f=fixture();const id=create(f);submitOfferForApprovalInTransaction(f.org,f.admin,id);approveOfferInTransaction(f.org,f.hr,id);const o=getOffer(f.org,id);assert.equal(o.status,'approved');assert.equal(o.approved_by,f.hr)});
test('employee cannot approve',()=>{const f=fixture();const id=create(f);submitOfferForApprovalInTransaction(f.org,f.admin,id);assert.throws(()=>approveOfferInTransaction(f.org,f.emp,id),/active HR\/Admin/i)});
test('rejection requires a reason',()=>{const f=fixture();const id=create(f);submitOfferForApprovalInTransaction(f.org,f.admin,id);assert.throws(()=>rejectOfferInTransaction(f.org,f.hr,id,''),/Rejection reason/i)});
test('rejected offer is retained',()=>{const f=fixture();const id=create(f);submitOfferForApprovalInTransaction(f.org,f.admin,id);rejectOfferInTransaction(f.org,f.hr,id,'Budget review');assert.equal(getOffer(f.org,id).status,'rejected');assert.equal(getOffer(f.org,id).rejection_reason,'Budget review')});
test('approved terms cannot be changed',()=>{const f=fixture();const id=create(f);submitOfferForApprovalInTransaction(f.org,f.admin,id);approveOfferInTransaction(f.org,f.hr,id);assert.throws(()=>sqlite.prepare("UPDATE offers SET base_salary_minor=1 WHERE organization_id=? AND id=?").run(f.org,id),/immutable/i)});
test('sent terms cannot be changed',()=>{const f=fixture();const id=create(f);submitOfferForApprovalInTransaction(f.org,f.admin,id);approveOfferInTransaction(f.org,f.hr,id);sendOfferInTransaction(f.org,f.hr,id);assert.throws(()=>sqlite.prepare("UPDATE offers SET currency='USD' WHERE organization_id=? AND id=?").run(f.org,id),/immutable/i)});
test('revision preserves historical terms',()=>{const f=fixture();const id=create(f);submitOfferForApprovalInTransaction(f.org,f.admin,id);approveOfferInTransaction(f.org,f.hr,id);const rev=replaceOfferInTransaction(f.org,f.hr,id);assert.equal(getOffer(f.org,id).status,'replaced');assert.equal(getOffer(f.org,rev).version,2);assert.equal(getOffer(f.org,rev).base_salary_minor,125000000)});
test('revision becomes the sole active offer',()=>{const f=fixture();const id=create(f);submitOfferForApprovalInTransaction(f.org,f.admin,id);rejectOfferInTransaction(f.org,f.hr,id,'Need revised package');const rev=replaceOfferInTransaction(f.org,f.hr,id);assert.equal(getOffer(f.org,rev).status,'draft');assert.equal((sqlite.prepare("SELECT COUNT(*) n FROM offers WHERE application_id=? AND status IN ('draft','pending_approval','approved','sent')").get(f.app) as {n:number}).n,1)});
test('send requires approval',()=>{const f=fixture();const id=create(f);assert.throws(()=>sendOfferInTransaction(f.org,f.hr,id),/approved/i)});
test('send issues cryptographically random response token',()=>{const f=fixture();const id=create(f);submitOfferForApprovalInTransaction(f.org,f.admin,id);approveOfferInTransaction(f.org,f.hr,id);const r=sendOfferInTransaction(f.org,f.hr,id);assert.equal(r.responseToken.length,43);const o=getOffer(f.org,id);assert.equal(o.candidate_response_token_hash,hashResponseToken(r.responseToken));assert.notEqual(r.responseToken,o.candidate_response_token_hash)});
test('withdrawal prevents response',()=>{const f=fixture();const id=create(f);submitOfferForApprovalInTransaction(f.org,f.admin,id);approveOfferInTransaction(f.org,f.hr,id);const r=sendOfferInTransaction(f.org,f.hr,id);withdrawOfferInTransaction(f.org,f.hr,id);assert.equal(getOffer(f.org,id).status,'withdrawn');assert.throws(()=>respondToOfferInTransaction({token:r.responseToken,decision:'accept',clientKey:'test'}),/no longer|invalid/i)});
test('acceptance is single-use and hires existing application',()=>{const f=fixture();const id=create(f);submitOfferForApprovalInTransaction(f.org,f.admin,id);approveOfferInTransaction(f.org,f.hr,id);const r=sendOfferInTransaction(f.org,f.hr,id);const result=respondToOfferInTransaction({token:r.responseToken,decision:'accept',clientKey:'test'});assert.equal(result.status,'accepted');assert.equal((sqlite.prepare('SELECT status FROM applications WHERE id=?').get(f.app) as {status:string}).status,'hired');assert.throws(()=>respondToOfferInTransaction({token:r.responseToken,decision:'accept',clientKey:'test'}),/no longer|invalid/i)});
test('decline stores sanitized bounded reason',()=>{const f=fixture();const id=create(f);submitOfferForApprovalInTransaction(f.org,f.admin,id);approveOfferInTransaction(f.org,f.hr,id);const r=sendOfferInTransaction(f.org,f.hr,id);respondToOfferInTransaction({token:r.responseToken,decision:'decline',reason:'Competing role <script>alert(1)</script>',clientKey:'test'});const o=getOffer(f.org,id);assert.equal(o.status,'declined');assert.equal(o.response_reason.includes('<script>'),true)});
test('acceptance after expiration is rejected',async()=>{const f=fixture();const id=createOfferInTransaction({organizationId:f.org,actorUserId:f.admin,applicationId:f.app,currency:'INR',baseSalaryMinor:1,payFrequency:'annual',expiresAt:new Date(Date.now()+250).toISOString()});submitOfferForApprovalInTransaction(f.org,f.admin,id);approveOfferInTransaction(f.org,f.hr,id);const r=sendOfferInTransaction(f.org,f.hr,id);await new Promise(resolve=>setTimeout(resolve,350));assert.throws(()=>respondToOfferInTransaction({token:r.responseToken,decision:'accept',clientKey:'test'}),/expired|no longer/i);assert.equal(getOffer(f.org,id).status,'expired')});
test('cross-tenant offer access fails',()=>{const f=fixture();const id=create(f);assert.equal(getOffer(f.other,id),null)});
test('cross-tenant offer mutation fails',()=>{const f=fixture();const id=create(f);assert.throws(()=>withdrawOfferInTransaction(f.other,f.admin,id),/not found|suspended/i)});
test('organization suspension blocks offer mutations',()=>{const f=fixture();const id=create(f);sqlite.prepare("UPDATE organizations SET status='suspended' WHERE id=?").run(f.org);assert.throws(()=>submitOfferForApprovalInTransaction(f.org,f.admin,id),/suspended/i)});
test('offer history is immutable',()=>{const f=fixture();const id=create(f);const h=sqlite.prepare('SELECT id FROM offer_history WHERE offer_id=? LIMIT 1').get(id) as any;assert.throws(()=>sqlite.prepare("UPDATE offer_history SET action='tampered' WHERE id=?").run(h.id),/immutable/i);assert.throws(()=>sqlite.prepare("DELETE FROM offer_history WHERE id=?").run(h.id),/immutable/i)});
test('offer hard delete is blocked',()=>{const f=fixture();const id=create(f);assert.throws(()=>sqlite.prepare('DELETE FROM offers WHERE id=?').run(id),/hard-delete|cannot be hard-deleted/i)});
test('offer document column exists and is indexed',()=>{assert.ok(sqlite.prepare("SELECT 1 FROM pragma_table_info('candidate_documents') WHERE name='offer_id'").get());assert.ok(sqlite.prepare("SELECT 1 FROM sqlite_master WHERE type='index' AND name='candidate_documents_offer_idx'").get())});
test('money formatter uses currency minor-unit precision',()=>{assert.match(formatMoneyMinor(125000000,'INR'),/1,250,000/);assert.match(formatMoneyMinor(123,'USD'),/1\.23/)});
test('response tokens are unique and hashed',()=>{const a=generateResponseToken(),b=generateResponseToken();assert.notEqual(a,b);assert.equal(hashResponseToken(a).length,64);assert.notEqual(a,hashResponseToken(a))});
test('offer reference is not the internal id',()=>{const f=fixture();const id=create(f);const o=getOffer(f.org,id);assert.notEqual(o.offer_reference,id);assert.match(o.offer_reference,/^OFF-\d{4}-\d{6}$/)});
test('application tenant constraint blocks injected candidate',()=>{const f=fixture();assert.throws(()=>sqlite.prepare("INSERT INTO applications (id,organization_id,candidate_id,requisition_id,application_reference,status,current_stage) VALUES ('inj','${f.org}','missing','${f.job}','INJ','evaluation','evaluation')").run(),/FOREIGN KEY/i)});
test('offer document ownership trigger rejects mismatched offer',()=>{const f=fixture();const id=create(f);assert.throws(()=>sqlite.prepare("INSERT INTO candidate_documents (id,organization_id,candidate_id,application_id,offer_id,document_type,original_filename,sanitized_filename,detected_mime_type,file_size,storage_provider,storage_key,checksum_sha256,uploaded_by) VALUES ('docx',?,?,?,?,?,?,?,?,?,?,?,?,?)").run(f.org,f.cand,f.app,'missing','other','x.txt','x.txt','text/plain',1,'local','documents/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb','a'.repeat(64),f.admin),/Offer document ownership/i)});
