import Link from 'next/link';
import { requireUser } from '@/lib/auth';
import { listInterviews } from '@/lib/recruitment-workflow';

export default async function InterviewsPage({searchParams}:{searchParams:Promise<{status?:string}>}){
  const u=await requireUser(); const p=await searchParams; const status=p.status||'';
  const rows=listInterviews(u.organizationId,status,'','',u.role==='employee'?u.id:'');
  return <div className="max-w-7xl space-y-6"><div className="flex items-center justify-between gap-4"><div><p className="text-sm font-medium text-brand-600">Recruitment / Interviews</p><h1 className="mt-1 text-2xl font-semibold">Interview schedule</h1><p className="mt-1 text-sm text-surface-500">{u.role==='employee'?'Your assigned interviews.':'Organization interview schedule.'}</p></div>{u.role!=='employee'&&<Link className="btn-primary" href="/recruitment/interviews/new">Schedule interview</Link>}</div><form className="card p-4 flex flex-wrap gap-3 items-end"><div className="w-full sm:w-64"><label className="label">Status</label><select className="input" name="status" defaultValue={status}><option value="">All</option>{['scheduled','confirmed','completed','cancelled','rescheduled','no_show'].map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></div><button className="btn-secondary">Filter</button></form><div className="card overflow-x-auto">{rows.length===0?<div className="p-10 text-center text-sm text-surface-500">No interviews match the current filter.</div>:<table className="w-full text-sm"><thead><tr className="border-b border-surface-200 text-left text-xs uppercase text-surface-500"><th className="px-4 py-3">Interview</th><th className="px-4 py-3">Candidate / Job</th><th className="px-4 py-3">When</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Panel</th></tr></thead><tbody>{rows.map((r:any)=><tr className="border-b border-surface-100 last:border-0" key={r.id}><td className="px-4 py-3"><Link className="font-medium text-brand-600 hover:underline" href={`/recruitment/interviews/${r.id}`}>{r.title}</Link><p className="text-xs text-surface-500">{r.application_reference}</p></td><td className="px-4 py-3">{r.first_name} {r.last_name}<p className="text-xs text-surface-500">{r.requisition_code} — {r.job_title}</p></td><td className="px-4 py-3"><time dateTime={r.scheduled_start}>{new Date(r.scheduled_start).toLocaleString('en-IN',{timeZone:r.timezone})}</time><p className="text-xs text-surface-500">{r.timezone}</p></td><td className="px-4 py-3"><span className={r.status==='completed'?'badge-green':r.status==='cancelled'||r.status==='no_show'?'badge-gray':'badge-amber'}>{r.status.replaceAll('_',' ')}</span></td><td className="px-4 py-3">{r.participant_count}</td></tr>)}</tbody></table>}</div></div>;
}
